# -*- encoding: utf-8 -*-

=begin
#Topological Inventory

#Topological Inventory

The version of the OpenAPI document: 3.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

$:.push File.expand_path("../lib", __FILE__)
require "topological_inventory-api-client/version"

Gem::Specification.new do |s|
  s.name        = "topological_inventory-api-client"
  s.version     = TopologicalInventoryApiClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = ["support@redhat.com"]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Topological Inventory Ruby Gem"
  s.description = "Topological Inventory"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
