=begin
#Topological Inventory

#Topological Inventory

The version of the OpenAPI document: 2.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.1

=end

module TopologicalInventoryApiClient
  VERSION = '1.0.0'
end
