=begin
#Topological Inventory

#Topological Inventory

OpenAPI spec version: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

module TopologicalInventoryApiClient
  VERSION = '1.0.0'
end
